import 'package:finance_app/core/payment_schedule/domain/installment.dart';
import 'package:finance_app/core/payment_schedule/domain/owner_type.dart';
import 'package:finance_app/features/expense/domain/expense.dart';
import 'package:finance_app/features/expense/domain/expense_participant.dart';
import 'package:finance_app/features/expense/domain/split_type.dart';
import 'package:finance_app/features/expense/presentation/widgets/share_expense.dart';
import 'package:flutter_test/flutter_test.dart';

Expense _expense({required List<ExpenseParticipant> participants}) {
  return Expense(
    id: 'exp1',
    description: 'Dinner at BBQ Nation',
    totalAmount: 3000,
    date: DateTime(2026, 7, 2),
    categoryId: 'cat1',
    accountId: 'acc1',
    transactionId: 'txn1',
    splitType: SplitType.equal,
    participants: participants,
    scheduleId: 'sched1',
    createdAt: DateTime(2026, 7, 2),
  );
}

Installment _installment({required String id, double amountDue = 1000, double amountPaid = 0}) {
  return Installment(
    id: id,
    scheduleId: 'sched1',
    ownerType: OwnerType.splitExpense,
    ownerId: 'exp1',
    sequenceNumber: 1,
    dueDate: DateTime(2026, 7, 2),
    amountDue: amountDue,
    amountPaid: amountPaid,
    createdAt: DateTime(2026, 7, 2),
  );
}

void main() {
  group('ShareExpense.buildText', () {
    test('includes FLOWFI branding, expense info, and per-participant split details', () {
      final rahul = ExpenseParticipant(name: 'Rahul', share: 1000, personId: 'p-rahul', installmentId: 'inst-rahul');
      final arjun = ExpenseParticipant(name: 'Arjun', share: 1000, personId: 'p-arjun', installmentId: 'inst-arjun');
      final me = ExpenseParticipant(name: 'Me', share: 1000, isMe: true);

      final expense = _expense(participants: [rahul, arjun, me]);
      final installments = [
        _installment(id: 'inst-rahul', amountPaid: 0),
        _installment(id: 'inst-arjun', amountPaid: 500),
      ];

      final text = ShareExpense.buildText(expense, installments);

      expect(text, contains('FLOWFI'));
      expect(text, contains('Dinner at BBQ Nation'));
      expect(text, contains('Rahul'));
      expect(text, contains('Arjun'));
      expect(text, contains('Me'));
      expect(text, contains('🔴')); // Rahul: nothing paid
      expect(text, contains('🟠')); // Arjun: partially paid
      expect(text, contains('✅')); // Me: own share
      expect(text, contains('Generated by FlowFi'));
    });

    test('computes collected and remaining across all participant installments', () {
      final rahul = ExpenseParticipant(name: 'Rahul', share: 1000, personId: 'p-rahul', installmentId: 'inst-rahul');
      final expense = _expense(participants: [rahul]);
      final installments = [_installment(id: 'inst-rahul', amountDue: 1000, amountPaid: 400)];

      final text = ShareExpense.buildText(expense, installments);

      expect(text, contains('Collected: ₹400.00'));
      expect(text, contains('Remaining: ₹600.00'));
    });
  });
}
