import '../../../../core/payment_schedule/domain/installment_status.dart';
import '../../domain/person_timeline_entry.dart';

/// Pure string-building helpers shared by [ShareStatement] and
/// `ShareExpense` — the FLOWFI-branded visual language (header, footer,
/// dividers, status dots) both formatters wrap their content in. No
/// widgets, no `BuildContext`; plain string construction only, so it's
/// trivially unit-testable the same way `PersonTimelineBuilder` is.
abstract class ShareFormat {
  ShareFormat._();

  static const divider = '=========================================';

  static String header(String title) => '$divider\n💸 FLOWFI\n$title\n$divider';

  static const footer = '$divider\nGenerated by FlowFi\nYour Money. Clearly Managed.\n$divider';

  /// 🟢 fully paid, 🟠 partially paid, 🔴 pending/overdue, ⚪ no status.
  static String statusDot(PersonTimelineStatus? status) {
    switch (status) {
      case PersonTimelineStatus.completed:
        return '🟢';
      case PersonTimelineStatus.partial:
        return '🟠';
      case PersonTimelineStatus.pending:
      case PersonTimelineStatus.overdue:
        return '🔴';
      case null:
        return '⚪';
    }
  }

  /// Same visual language as [statusDot], keyed off [InstallmentStatus] for
  /// callers (like `ShareExpense`) working directly with a participant's
  /// tracking installment rather than a person-timeline entry.
  static String installmentStatusDot(InstallmentStatus status) {
    switch (status) {
      case InstallmentStatus.paid:
        return '🟢';
      case InstallmentStatus.partiallyPaid:
        return '🟠';
      case InstallmentStatus.overdue:
      case InstallmentStatus.upcoming:
      case InstallmentStatus.skipped:
        return '🔴';
    }
  }
}
