// File generated by FlutterFire CLI.
// THIS IS A PLACEHOLDER — run `flutterfire configure --project=financeapp-9b95e`
// to overwrite this file with real values before running the app.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'run `flutterfire configure --project=financeapp-9b95e` to generate real options.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform - '
          'run `flutterfire configure --project=financeapp-9b95e` to generate real options.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnhzV8Zw6RXAdEZX8CaasvLr-fcJ7gQ5Q',
    appId: '1:570188084565:android:0c7820ca8654808325ebdc',
    messagingSenderId: '570188084565',
    projectId: 'financeapp-585eb',
    storageBucket: 'financeapp-585eb.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxgzyGBoBKuuU1UOMXqypPyCKupD8ZI60',
    appId: '1:570188084565:ios:80f2efe469991ac825ebdc',
    messagingSenderId: '570188084565',
    projectId: 'financeapp-585eb',
    storageBucket: 'financeapp-585eb.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxgzyGBoBKuuU1UOMXqypPyCKupD8ZI60',
    appId: '1:570188084565:ios:80f2efe469991ac825ebdc',
    messagingSenderId: '570188084565',
    projectId: 'financeapp-585eb',
    storageBucket: 'financeapp-585eb.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCR1tKPRor--ND1--tmS72UyqWELBgm3UM',
    appId: '1:570188084565:web:2c1351d50b62789325ebdc',
    messagingSenderId: '570188084565',
    projectId: 'financeapp-585eb',
    authDomain: 'financeapp-585eb.firebaseapp.com',
    storageBucket: 'financeapp-585eb.firebasestorage.app',
    measurementId: 'G-GRFMSFHZ1Q',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR1tKPRor--ND1--tmS72UyqWELBgm3UM',
    appId: '1:570188084565:web:8016cc26cc7e9c1225ebdc',
    messagingSenderId: '570188084565',
    projectId: 'financeapp-585eb',
    authDomain: 'financeapp-585eb.firebaseapp.com',
    storageBucket: 'financeapp-585eb.firebasestorage.app',
    measurementId: 'G-H8ZBEH8QEE',
  );
}
