import 'package:finance_app/core/payment_schedule/domain/installment_status.dart';
import 'package:finance_app/features/people/domain/person_timeline_entry.dart';
import 'package:finance_app/features/people/presentation/widgets/share_format.dart';
import 'package:flutter_test/flutter_test.dart';

void main() {
  group('ShareFormat.header', () {
    test('wraps the title in FLOWFI branding and dividers', () {
      final header = ShareFormat.header('Statement for Rahul');
      expect(header, contains('FLOWFI'));
      expect(header, contains('Statement for Rahul'));
      expect(header, contains(ShareFormat.divider));
    });
  });

  group('ShareFormat.footer', () {
    test('credits FlowFi', () {
      expect(ShareFormat.footer, contains('Generated by FlowFi'));
      expect(ShareFormat.footer, contains(ShareFormat.divider));
    });
  });

  group('ShareFormat.statusDot', () {
    test('maps every PersonTimelineStatus to a distinct dot', () {
      expect(ShareFormat.statusDot(PersonTimelineStatus.completed), '🟢');
      expect(ShareFormat.statusDot(PersonTimelineStatus.partial), '🟠');
      expect(ShareFormat.statusDot(PersonTimelineStatus.pending), '🔴');
      expect(ShareFormat.statusDot(PersonTimelineStatus.overdue), '🔴');
      expect(ShareFormat.statusDot(null), '⚪');
    });
  });

  group('ShareFormat.installmentStatusDot', () {
    test('maps every InstallmentStatus to a distinct dot', () {
      expect(ShareFormat.installmentStatusDot(InstallmentStatus.paid), '🟢');
      expect(ShareFormat.installmentStatusDot(InstallmentStatus.partiallyPaid), '🟠');
      expect(ShareFormat.installmentStatusDot(InstallmentStatus.overdue), '🔴');
      expect(ShareFormat.installmentStatusDot(InstallmentStatus.upcoming), '🔴');
      expect(ShareFormat.installmentStatusDot(InstallmentStatus.skipped), '🔴');
    });
  });
}
