import 'package:pdf/widgets.dart' as pw;

import '../font_manager.dart';
import '../pdf_tokens.dart';

/// The brand footer repeated on every page — matches `ShareFormat.footer`'s
/// copy (minus the ASCII divider, which is a plain-text affordance, not a
/// document one) plus a "Page X of Y" page count supplied by
/// [pw.MultiPage]'s footer callback context.
class PdfFooter extends pw.StatelessWidget {
  PdfFooter({required this.pageNumber, required this.pagesCount, required this.fonts});

  final int pageNumber;
  final int pagesCount;
  final PdfFonts fonts;

  @override
  pw.Widget build(pw.Context context) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: PdfTokens.sm),
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(color: PdfTokens.outline, width: 0.5)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by FlowFi • Your Money. Clearly Managed.',
            style: pw.TextStyle(font: fonts.regular, fontSize: PdfTokens.fontCaption, color: PdfTokens.textSecondary),
          ),
          pw.Text(
            'Page $pageNumber of $pagesCount',
            style: pw.TextStyle(font: fonts.regular, fontSize: PdfTokens.fontCaption, color: PdfTokens.textSecondary),
          ),
        ],
      ),
    );
  }
}
